drop function if exists kimlik_pseudonimlestir(uuid);
drop function if exists hesap_ac(citext, text, text);
drop function if exists oturum_coz(text);
drop function if exists eposta_kayitli(citext);
drop function if exists giris_kimlik(citext);
drop function if exists oneri_taban_puani(bigint, jsonb);
drop function if exists etkin_puanlar(bigint);
drop function if exists nace_ust_kod(text);
drop trigger if exists degerlendirme_ham_puan_sabit_trg on degerlendirme;
drop function if exists degerlendirme_ham_puan_sabit();
drop trigger if exists denetim_delete_engel on denetim;
drop trigger if exists denetim_update_engel on denetim;
drop function if exists denetim_degistirilemez();
