drop view if exists kanit_kunye;
drop function if exists kimlik_pseudonimlestir(uuid);
drop function if exists oturum_coz(text);
drop function if exists eposta_kayitli(citext);
drop function if exists giris_kimlik(citext);
drop function if exists hesap_ac(citext, text, text, boolean);
drop function if exists destek_sayisi(bigint);
drop function if exists aday_epistemik(bigint, integer);
drop function if exists aday_taban_puani(bigint, jsonb);
drop function if exists oneri_kanit_yeterliligi(bigint);
drop function if exists kanit_potansiyeli(bigint);
drop function if exists kanit_yeterliligi(bigint);
drop trigger if exists donem_kilit_tek_yon_trg on donem;
drop function if exists donem_kilit_tek_yon();
drop trigger if exists kanit_kilit_engel on kanit;
drop trigger if exists aday_kilit_engel on aday;
drop trigger if exists oneri_kilit_engel on oneri;
drop function if exists kilitli_donem_yazma_engeli();
drop function if exists donem_kilitli_mi(bigint);
drop trigger if exists denetim_delete_engel on denetim;
drop trigger if exists denetim_update_engel on denetim;
drop function if exists denetim_degistirilemez();
